name: Continuous Deployment

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  run_pull:
    name: Run Pull and Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checking out code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set deployment variables
        run: |
          if [ "${{ github.ref }}" = "refs/heads/main" ]; then
            echo "IMAGE=bikego-main" >> $GITHUB_ENV
            echo "FLASK_ENV=${{ secrets.FLASK_ENV }}" >> $GITHUB_ENV
            echo "DB_USER=${{ secrets.DB_USER }}" >> $GITHUB_ENV
            echo "DB_PASSWORD=${{ secrets.DB_PASSWORD }}" >> $GITHUB_ENV
            echo "DB_HOST=${{ secrets.DB_HOST }}" >> $GITHUB_ENV
            echo "DB_PORT=${{ secrets.DB_PORT }}" >> $GITHUB_ENV
            echo "DB_NAME=${{ secrets.DB_NAME }}" >> $GITHUB_ENV
            echo "DB_SCHEMA_NAME=${{ secrets.DB_SCHEMA_NAME }}" >> $GITHUB_ENV
            echo "JWT_SECRET_KEY=${{ secrets.JWT_SECRET_KEY }}" >> $GITHUB_ENV
            echo "IMGUR_CLIENT_ID=${{ secrets.IMGUR_CLIENT_ID }}" >> $GITHUB_ENV
            echo "SENDER_EMAIL=${{ secrets.SENDER_EMAIL }}" >> $GITHUB_ENV
            echo "SENDER_PASSWORD=${{ secrets.SENDER_PASSWORD }}" >> $GITHUB_ENV
          else
            echo "Invalid branch for deployment" && exit 1
          fi

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Get the short SHA hash of the commit
        run: |
          echo "SHORT_SHA=$(git rev-parse --short HEAD)" >> $GITHUB_ENV

      - name: Build and push Docker image
        run: |
          docker build -t bikego/${{ env.IMAGE }}:${{ github.ref_name }}-${{ env.SHORT_SHA }} .
          docker push bikego/${{ env.IMAGE }}:${{ github.ref_name }}-${{ env.SHORT_SHA }}

      - name: Install OpenVPN
        run: |
          sudo apt-get update && sudo apt-get install openvpn -y

      - name: Configure OpenVPN
        run: |
          echo "${{ secrets.OPENVPN_CONFIG }}" > ~/openvpn-config.ovpn
          echo "${{ secrets.OPENVPN_PASSWORD }}" > ~/openvpn.txt

      - name: Connect to OpenVPN
        run: |
          sudo nohup openvpn --config ~/openvpn-config.ovpn --auth-nocache --askpass ~/openvpn.txt > /dev/null 2>&1 &

      - name: Wait for VPN Connection
        run: |
          while ! pgrep -x "openvpn" > /dev/null; do sleep 1; done

      - name: SSH into Your Server and Deploy
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            docker login || true && \
            docker pull bikego/${{ env.IMAGE }}:${{ github.ref_name }}-${{ env.SHORT_SHA }} && \
            docker ps -a | grep ${{ env.IMAGE }} && docker stop ${{ env.IMAGE }} || true && \
            docker ps -a | grep ${{ env.IMAGE }} && docker rm ${{ env.IMAGE }} || true && \
            docker run \
            -e FLASK_ENV="${{ secrets.FLASK_ENV }}" \
            -e DB_USER="${{ secrets.DB_USER }}" \
            -e DB_PASSWORD="${{ secrets.DB_PASSWORD }}" \
            -e DB_HOST="${{ secrets.DB_HOST }}" \
            -e DB_PORT="${{ secrets.DB_PORT }}" \
            -e DB_NAME="${{ secrets.DB_NAME }}" \
            -e DB_SCHEMA_NAME="${{ env.DB_SCHEMA_NAME }}" \
            -e JWT_SECRET_KEY="${{ secrets.JWT_SECRET_KEY }}" \
            -e IMGUR_CLIENT_ID="${{ secrets.IMGUR_CLIENT_ID }}" \
            -e SENDER_EMAIL="${{ secrets.SENDER_EMAIL }}" \
            -e SENDER_PASSWORD="${{ secrets.SENDER_PASSWORD }}" \
            --name ${{ env.IMAGE }} -d -p ${{ env.DEFAULT_PORT }}:${{ env.DEFAULT_PORT }} \
            bikego/${{ env.IMAGE }}:${{ github.ref_name }}-${{ env.SHORT_SHA }} && \
            docker update --restart unless-stopped ${{ env.IMAGE }} && exit

      - name: Close OpenVPN Connection
        run: |
          sudo pkill openvpn

      - name: Clean up SSH Configuration
        run: |
          rm -rf ~/.ssh