name: Continuous Deployment

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Docker Image
        run: |
          SHORT_SHA=$(git rev-parse --short HEAD)
          docker build -t selecro/bikego-main:${{ github.ref_name }}-${SHORT_SHA} -t selecro/bikego-main:latest .
          docker push selecro/bikego-main:${{ github.ref_name }}-${SHORT_SHA}
          docker push selecro/bikego-main:latest

      - name: Set up and Connect to OpenVPN
        run: |
          echo "${{ secrets.OPENVPN_CONFIG }}" | base64 -d > ~/openvpn-config.ovpn
          sudo openvpn --config ~/openvpn-config.ovpn --auth-nocache --daemon

      - name: Deploy Files via SFTP
        uses: Dylan700/sftp-upload-action@v1.2.3
        with:
          server: ${{ secrets.SERVER_IP }}
          port: ${{ secrets.SSH_PORT }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          uploads: "./ => bikego"

      - name: Deploy and Start Docker Compose
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            > ~/bikego/.env
            vars=("POSTGRES_USER" "POSTGRES_PASSWORD" "POSTGRES_DB" "POSTGRES_HOST" "POSTGRES_PORT" 
                  "POSTGRES_SCHEMA" "PGADMIN_DEFAULT_EMAIL" "PGADMIN_DEFAULT_PASSWORD" 
                  "FLASK_APP" "FLASK_ENV" "FLASK_HOST" "FLASK_PORT" 
                  "JWT_SECRET_KEY" "SECRET_KEY" "IMGUR_CLIENT_ID" 
                  "IMGUR_CLIENT_SECRET" "SENDER_EMAIL" "SENDER_PASSWORD" "URL_IN_EMAIL")
            for var in "${vars[@]}"; do
                echo "${var}=${{ secrets[$var] }}" >> ~/bikego/.env
            done
            cd ~/bikego
            docker-compose down
            docker-compose up -d --build
            docker-compose logs

      - name: Clean Up Temporary Files
        run: |
          rm -rf ~/openvpn-config.ovpn ~/.ssh
