name: Continuous Deployment

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  # Job 1: Setup Environment
  setup:
    name: Setup Environment Variables
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set Deployment Variables
        if: github.ref == 'refs/heads/main'
        run: |
          echo "IMAGE=bikego-main" >> $GITHUB_ENV

  # Job 2: Build and Push Docker Image
  build:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest
    needs: setup

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Get Short SHA for Docker Tag
        run: |
          SHORT_SHA=$(git rev-parse --short HEAD)
          echo "SHORT_SHA=$SHORT_SHA" >> $GITHUB_ENV

      - name: Build Docker Image
        run: |
          echo "Building Docker image with tag selecro/bikego-main:${{ github.ref_name }}-${{ env.SHORT_SHA }}"
          docker build -t selecro/bikego-main:${{ github.ref_name }}-${{ env.SHORT_SHA }} .

      - name: Push Docker Image
        run: |
          docker push selecro/bikego-main:${{ github.ref_name }}-${{ env.SHORT_SHA }}

  # Job 3: Setup VPN Connection
  vpn_setup:
    name: Establish VPN Connection
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Install OpenVPN
        run: sudo apt-get update && sudo apt-get install openvpn -y

      - name: Configure OpenVPN
        run: |
          echo "${{ secrets.OPENVPN_CONFIG }}" > ~/openvpn-config.ovpn
          echo "${{ secrets.OPENVPN_PASSWORD }}" > ~/openvpn.txt

      - name: Connect to OpenVPN
        run: |
          sudo nohup openvpn --config ~/openvpn-config.ovpn --auth-nocache --askpass ~/openvpn.txt > /dev/null 2>&1 &

      - name: Wait for VPN Connection
        run: |
          while ! pgrep -x "openvpn" > /dev/null; do sleep 1; done

  # Job 4: Deploy Application to Server
  deploy:
    name: Deploy Application
    runs-on: ubuntu-latest
    needs: vpn_setup

    steps:
      - name: SSH Deploy and Run Docker Container
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            docker login || true
            docker pull selecro/bikego-main:${{ github.ref_name }}-${{ env.SHORT_SHA }}
            docker stop bikego-main || true
            docker rm bikego-main || true
            docker run -d --name bikego-main \
              -e HOST="${{ secrets.HOST }}" \
              -e PORT="${{ secrets.PORT }}" \
              -e FLASK_ENV="${{ secrets.FLASK_ENV }}" \
              -e DB_USER="${{ secrets.DB_USER }}" \
              -e DB_PASSWORD="${{ secrets.DB_PASSWORD }}" \
              -e DB_HOST="${{ secrets.DB_HOST }}" \
              -e DB_PORT="${{ secrets.DB_PORT }}" \
              -e DB_NAME="${{ secrets.DB_NAME }}" \
              -e DB_SCHEMA_NAME="${{ secrets.DB_SCHEMA_NAME }}" \
              -e JWT_SECRET_KEY="${{ secrets.JWT_SECRET_KEY }}" \
              -e IMGUR_CLIENT_ID="${{ secrets.IMGUR_CLIENT_ID }}" \
              -e SENDER_EMAIL="${{ secrets.SENDER_EMAIL }}" \
              -e SENDER_PASSWORD="${{ secrets.SENDER_PASSWORD }}" \
              -p ${{ secrets.DEFAULT_PORT }}:${{ secrets.DEFAULT_PORT }} \
              selecro/bikego-main:${{ github.ref_name }}-${{ env.SHORT_SHA }}
            docker update --restart unless-stopped bikego-main

  # Job 5: Cleanup Resources
  cleanup:
    name: Cleanup VPN and Temporary Files
    runs-on: ubuntu-latest
    needs: deploy

    steps:
      - name: Terminate OpenVPN Connection
        run: sudo pkill -f openvpn || true

      - name: Remove Temporary Files
        run: rm -rf ~/openvpn-config.ovpn ~/vpn-auth.txt ~/.ssh

      - name: Delete OpenVPN Password
        run: rm -rf ~/openvpn.txt|| true